[template]

[placeholders]
backend = { prompt = "What backend framework are you using?", type = "string", choices = [
    "Axum",
    "Warp",
    "Salvo",
], default = "Axum" }
router = { prompt = "Should the application use the Dioxus router?", type = "bool", default = true }
styling = { prompt = "How do you want to create CSS?", choices = [
    "Tailwind",
    "Vanilla",
], default = "Vanilla", type = "string" }


[conditional.'styling == "Vanilla"']
ignore = ["tailwind.config.js", "input.css"]
